[tool.poetry]
name = "figure-tools"
version = "0.1.1"
description = ""
authors = ["thaeber"]

[tool.poetry.dependencies]
python = ">=3.5"
matplotlib = ">=3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
